/** Cấu hình lấy nguyên văn từ tailwind-config trong Stitch UI (các trang đều giống nhau). */
/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-container': '#be123c',
        'secondary-fixed-dim': '#68dba9',
        'on-background': '#1a1c1b',
        'on-tertiary-container': '#ffd2b1',
        'primary-fixed-dim': '#ffb2b7',
        'tertiary-fixed': '#ffdcc3',
        background: '#faf9f7',
        'on-secondary-fixed-variant': '#005137',
        'secondary-container': '#82f5c1',
        'on-surface': '#1a1c1b',
        'surface-container-highest': '#e3e2e0',
        'on-primary-container': '#ffd0d2',
        'inverse-surface': '#2f3130',
        'on-error': '#ffffff',
        'surface-container-high': '#e9e8e6',
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#faf9f7',
        'tertiary-fixed-dim': '#ffb77d',
        'primary-fixed': '#ffdadb',
        'surface-dim': '#dadad8',
        'outline-variant': '#e3bdbf',
        'on-surface-variant': '#5b4041',
        outline: '#8f6f70',
        'surface-tint': '#bb0f3a',
        'on-primary': '#ffffff',
        surface: '#faf9f7',
        error: '#ba1a1a',
        'on-primary-fixed-variant': '#920029',
        'tertiary-container': '#934e00',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#40000d',
        'on-tertiary-fixed-variant': '#6e3900',
        secondary: '#006c4a',
        'secondary-fixed': '#85f8c4',
        'surface-container-low': '#f4f3f1',
        'inverse-on-surface': '#f1f1ef',
        'surface-variant': '#e3e2e0',
        primary: '#95002a',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed': '#2f1500',
        'on-secondary-fixed': '#002114',
        'inverse-primary': '#ffb2b7',
        'on-secondary-container': '#00714e',
        'on-error-container': '#93000a',
        'surface-container': '#efeeec',
        tertiary: '#703a00',
        'error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-sm': '0.5rem',
        'space-xl': '2.5rem',
        'margin-sm': '1rem',
        'space-md': '1rem',
        margin: '2rem',
        gutter: '1.5rem',
        'space-xs': '0.25rem',
        'space-lg': '1.5rem',
        'gutter-sm': '1rem',
      },
      fontFamily: {
        'headline-lg': ['Plus Jakarta Sans'],
        'display-character': ['Noto Serif'],
        'display-character-mobile': ['Noto Serif'],
        'label-sm': ['Plus Jakarta Sans'],
        'title-sm': ['Plus Jakarta Sans'],
        'body-sm': ['Plus Jakarta Sans'],
        'headline-xl': ['Noto Serif'],
        'body-lg': ['Plus Jakarta Sans'],
        'headline-xl-mobile': ['Noto Serif'],
        'body-md': ['Plus Jakarta Sans'],
        'label-md': ['Plus Jakarta Sans'],
        'headline-md': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'headline-lg': [
          '24px',
          {
            lineHeight: '32px',
            letterSpacing: '-0.015em',
            fontWeight: '700',
          },
        ],
        'display-character': [
          '96px',
          {
            lineHeight: '112px',
            letterSpacing: '0px',
            fontWeight: '600',
          },
        ],
        'display-character-mobile': [
          '64px',
          {
            lineHeight: '76px',
            letterSpacing: '0px',
            fontWeight: '600',
          },
        ],
        'label-sm': [
          '11px',
          {
            lineHeight: '16px',
            letterSpacing: '0.06em',
            fontWeight: '700',
          },
        ],
        'title-sm': [
          '16px',
          {
            lineHeight: '24px',
            letterSpacing: '-0.005em',
            fontWeight: '600',
          },
        ],
        'body-sm': [
          '13px',
          {
            lineHeight: '20px',
            letterSpacing: '0.01em',
            fontWeight: '400',
          },
        ],
        'headline-xl': [
          '36px',
          {
            lineHeight: '44px',
            letterSpacing: '-0.02em',
            fontWeight: '700',
          },
        ],
        'body-lg': [
          '18px',
          {
            lineHeight: '28px',
            letterSpacing: '0',
            fontWeight: '400',
          },
        ],
        'headline-xl-mobile': [
          '28px',
          {
            lineHeight: '36px',
            letterSpacing: '-0.01em',
            fontWeight: '700',
          },
        ],
        'body-md': [
          '15px',
          {
            lineHeight: '24px',
            letterSpacing: '0',
            fontWeight: '400',
          },
        ],
        'label-md': [
          '13px',
          {
            lineHeight: '18px',
            letterSpacing: '0.02em',
            fontWeight: '600',
          },
        ],
        'headline-md': [
          '20px',
          {
            lineHeight: '28px',
            letterSpacing: '-0.01em',
            fontWeight: '600',
          },
        ],
      },
    },
  },
};
